FROM node:22-slim AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build
FROM caddy:2.9
COPY --from=build /app/dist /usr/share/caddy
COPY deploy/front.Caddyfile /etc/caddy/Caddyfile
